### ISSUE TITLE
User sessions

### ISSUE THREAD

**Issue by ghost** [corrego/Parse.AspNet.Identity#1]
Hi,

Im not sure if I'm posting in the right place, but I tried to look for your contact but I couldn't. Ima having an issue with your solution using the new authentication method Identity.

So the thing is, I have my app running over the IIS with multiple users connected. When I login with the user A and keep this session open, let's say in my Chrome browser, and then I login in the same computer but using Firefox with the user B, when I make an insertion in my dabatase with the user A I get an error: UserCannotBeAlteredWithoutSessionError

Is it because Parse is working with one logged user per device?

**Comment by corrego** [comment]
Hmm it's a good question. When you say you make an insert in your database, you mean Parse? or your local DB? Do you have example code that shows the issue so I can look at it?

**Comment by ghost** [comment]
Hey thanks for the fast reply. I just found the error, actually it was my
fault. But I think that would be a nice idea to include it in your
documentation.
If your are trying to get the current user to use as a reference in some
object you must use the code below:

Var store = new Parse.AspNet.Identity.ParseUserStore<ApplicationUser>();
Var userManager = new UserManager<ApplicationUser>(store);
Var myUser = userManager.FindyById(User.Identity.GetUserId());

//to create the reference
Foo foo = new Foo();
foo.owner = ParseUser.CreateWithoutData<ParseUser>(myUser.Id);

 instead of ParseUser.currentUser from the parse sdk otherwise you would
get a null pointer in your parse database, once the parse only handle one
user per device (it loses the reference of the current user each time that
the app server send a login requisition).

I'm not sure why I was getting the exception, but seems it was solved.

On Monday, February 2, 2015, corrego notifications@github.com wrote:

> Hmm it's a good question. When you say you make an insert in your
> database, you mean Parse? or your local DB? Do you have example code that
> shows the issue so I can look at it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/corrego/Parse.AspNet.Identity/issues/1#issuecomment-72489231
> .

## 

Yours sincerely,
Bruno Casarotti

**Comment by corrego** [comment]
awesome! thanks for sharing, I will make sure to update the docs when I have a chance.

My best guess is that the CurrentUser is getting lost between requests. I don't know how the Parse sdk saves the current user internally after you log in. I hope they don't do it in a static variable because that would effectively limit you to one user per application instance (!). 

For now, your solution looks good, although I would like to add the user Id to the claims, so you can do var id = User.Identity.GetUserId() (or whatever the extension method is called)

Thanks!
