### ISSUE TITLE
Missing class ParseApplicationUserBase

### ISSUE THREAD

**Issue by mvcninja** [corrego/Parse.AspNet.Identity#2]
Readme mentions subclassing from **ParseApplicationUserBase** class, but it's nowhere to be found.
If I subclass off of IdentityUser, I get an error stating **PasswordHash** property is missing.

**Comment by VladimirUA** [comment]
Same story :-1:

**Comment by corrego** [comment]
There is a mismatch between the docs and a botched commit that I didn't realize before -- I'm working on it :) The class you're looking for is `Parse.AspNet.Identity.IdentityUser.` I will rename it to `ParseIdentityUser` because it creates confusion.

**Comment by corrego** [comment]
Fixed in 0.5.1
