### ISSUE TITLE
Parse.AspNet.Identity.ParseUserStore`1.GetAccessFailedCountAsync(TUser user)

### ISSUE THREAD

**Issue by mvcninja** [corrego/Parse.AspNet.Identity#3]
When logging in as an existing user, I get a **NotImplementedException** thrown at
**Parse.AspNet.Identity.ParseUserStore<TUser>.GetAccessFailedCountAsync(TUser user)**.
This method is not marked as virtual, so I cannot override it.

**Comment by corrego** [comment]
Yes, this is effectively not implemented. I believe that we can't update any user fields on a failed login (except with some master key trickery -- can't get into that ATM). This issue however didn't show up and I can't seem to trigger it now. What's your use case? Can you provide code and/or more info?

Thanks

**Comment by corrego** [comment]
Fixed in 0.5.1
